// flow-typed signature: f42bc5311d0faa1a49d230f5b3012898
// flow-typed version: <<STUB>>/svg-to-jsx-loader_v^2.0.1/flow_v0.66.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'svg-to-jsx-loader'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'svg-to-jsx-loader' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'svg-to-jsx-loader/index' {
  declare module.exports: $Exports<'svg-to-jsx-loader'>;
}
declare module 'svg-to-jsx-loader/index.js' {
  declare module.exports: $Exports<'svg-to-jsx-loader'>;
}
