// flow-typed signature: 21c23a4f6b6866a0b95f931da9cc2147
// flow-typed version: <<STUB>>/webpack-blocks_v^1.0.0-rc.2/flow_v0.66.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'webpack-blocks'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'webpack-blocks' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'webpack-blocks/index' {
  declare module.exports: $Exports<'webpack-blocks'>;
}
declare module 'webpack-blocks/index.js' {
  declare module.exports: $Exports<'webpack-blocks'>;
}
