// flow-typed signature: ec1c1b57dccd08b83e850e1adb1fe999
// flow-typed version: <<STUB>>/@mapbox/svg-react-transformer-loader_v^1.0.1/flow_v0.66.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@mapbox/svg-react-transformer-loader'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@mapbox/svg-react-transformer-loader' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module '@mapbox/svg-react-transformer-loader/index' {
  declare module.exports: $Exports<'@mapbox/svg-react-transformer-loader'>;
}
declare module '@mapbox/svg-react-transformer-loader/index.js' {
  declare module.exports: $Exports<'@mapbox/svg-react-transformer-loader'>;
}
